apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-v1
  labels:
    version: v1
    app: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
      version: v1
  template:
    metadata:
      labels:
        version: v1
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: manu756/app_for_demo:v1
        ports:
        - containerPort: 3000

