apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  type: NodePort
  selector:
    app: nodejs-app
    version: v1
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30001
